FROM python:3.13.1-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY fastapi/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend code
COPY fastapi/app ./app   

# Expose FastAPI port
EXPOSE 8000

# Run FastAPI app
CMD ["uvicorn", "app.application:app", "--host", "0.0.0.0", "--port", "8000"]
